### ISSUE TITLE
Game crash upon being hit by arrow or fire charge from Dispenser

### ISSUE THREAD

**Issue by floral-qua-floral** [mosharky/GroundedOrigins#11]
### Minecraft, Loader, & Mod Versions

* Minecraft 1.19
* Fabric loader 0.14.8
* Fabric API 0.50.0
* Origins 1.6.2
* Pehkui 3.3.3
* Grounded Origins 1.2.1

### Describe your issue

When the player is hit by an arrow or a fire charge that was shot by a dispenser, the game crashes immediately. In the moment before the window closes, the screen does tilt and the damage sound effect does play, but the player's health bar doesn't visually update. If the player was hit by an arrow, upon relaunching and re-entering the world, the arrow will still be in the world, with a small amount of backwards momentum as if it had been blocked by a shield. Some health will also be missing. If it was a potion arrow, they will not have the potion effect, but they will still be missing some health. If the player was hit by a fire charge, upon re-entering the world, the fire charge projectile will be gone, and the player will be on fire.

The game does not crash if the player is hit by a firework rocket or a Splash Potion of Harming from a Dispenser. The game also does not crash if the player is hit by an arrow from a Skeleton, Pillager, or themself (I didn't test arrows from _other_ players but I'd assume they also don't crash), or by a fire charge shot from a Blaze.

I've been testing the issue with just the Human origin, rather than one from this mod. Removing this mod fixes the issue.

### Crash reports
Crash report when hit by arrow: [crash-2022-07-19_11.14.35-server.txt](https://github.com/Mos-Origins/GroundedOrigins/files/9143681/crash-2022-07-19_11.14.35-server.txt)
Crash report when hit by an Arrow of Poison (11-second duration): [crash-2022-07-19_11.24.29-server.txt](https://github.com/Mos-Origins/GroundedOrigins/files/9143718/crash-2022-07-19_11.24.29-server.txt)
Crash report when hit by fire charge: [crash-2022-07-19_11.11.03-server.txt](https://github.com/Mos-Origins/GroundedOrigins/files/9143682/crash-2022-07-19_11.11.03-server.txt)

**Comment by mosharky** [comment]
I'll try to reproduce this and I'll get back to you. It's probably an issue with Apugli since my mod doesn't touch damage function stuff.

**Comment by mosharky** [comment]
It was Apugli. The update will go up shortly, thanks for the in-depth report!
