### ISSUE TITLE
moths cant eat certain foods

### ISSUE THREAD

**Issue by sparrowpaws** [mosharky/GroundedOrigins#12]
So players on my server have told me that they can't eat books, paper, leather, or string as a moth. I've tested and I'm having the same issue. Flower stamens and the other food sources such as apples and carrots work fine.
The version we are using is grounded_origins-fabric-1.18.2-1.2.0, as it is a 1.18.2 Fabric server.
I attached a list with all the mods we have. 
[modlist.txt](https://github.com/Mos-Origins/GroundedOrigins/files/9229394/modlist.txt)
It's probably something stupid that I'm not realizing, or a mod conflict, but I'm not sure.

**Comment by mosharky** [comment]
I can eat them just fine in the dev environment. It's probably an incompatibility with another mod. Eating items is handled through Apugli, not my mod, so head to the [Apugli issues page](https://github.com/MerchantPug/apugli/issues) if you manage to find what mod causes this. I don't have much time to test things out myself beyond confirming that it's a compatibility issue between Apugli and another mod.

**Comment by sparrowpaws** [comment]
Okay! I'll leave a note there then! Thanks!
