### ISSUE TITLE
Compatibility with vanilla tweak's unpackable wool.

### ISSUE THREAD

**Issue by Flyvee** [mosharky/GroundedOrigins#13]
### Minecraft Version

1.19.2

### Mod Version

v1.2.2

### Mod loader

Fabric

### Describe your issue

My server makes use of quite a few of the crafting tweaks and datapacks from vanilla tweaks including unpackable wool which makes it that you can convert 1 wool into 4 strings, but this mod's fibrous diet power overwrites that recipe for moths, is there a way for me to add more priority to the vanilla tweak's recipe or should I make a datapack that overwrites the fibrous diet power without the crafting power?

**Comment by mosharky** [comment]
You can use [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric) to cycle through recipes with similar inputs. You can also use [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs) or [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) to edit the recipe
