### ISSUE TITLE
Crash Upon Origin Selection

### ISSUE THREAD

**Issue by UncleLarry151** [mosharky/GroundedOrigins#14]
### Minecraft Version

1.18.2

### Mod Version

1.2.0

### Mod loader

Forge

### Describe your issue

Hi there!

I'm having difficulty with the forge version of this mod on a server of mine, particularly the moth origin. When I select it, the game stutters before disconnecting me from the server before I can select my class. The message I am given when I am kicked is "Internal server error" and I receive the "disconnected" message whenever I try to join the server again. My friend is able to play on it just fine, selecting his origin and class. As long as I do not pick moth (though this is the only origin I've tested from this mod, it's possible _none_ of them work) I am able to play just fine.

Modlist is considerably lengthy, but I do not believe the problem is due to a conflict. Here are the logs from the server when I select the moth origin. I suspect Apoli is causing the problem?

[30Nov2022 18:17:52.743] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @7a8341c1; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @7a8341c1)

Some help would be appreciated! For now I'll just play a different origin, thanks!

**Comment by mosharky** [comment]
And this doesn't happen in singleplayer?

**Comment by UncleLarry151** [comment]
> And this doesn't happen in singleplayer?

In singleplayer, the game full on entirely crashes. The only thing that's strange to me is that the server seems fine even after I select it.

Just tested it with an origin from bucolic origins, particularly the phantom one. This time I was able to select a class, but faced the same problem. Now I'm willing to bet it's an origins problem period, but came here first since I noticed your origins to be the first ones to present problems. Not sure why some work, and some don't, but apoli seems to be causing the brunt of the issues.

Any ideas as to what I should do first? Or do you think this question would be better suited towards the origin's forge port community? Not sure where to go from here.

**Comment by mosharky** [comment]
So sorry! I thought I had replied already. Yes, I'd take this question to the forge port repo instead of here. There's a very good chance I have nothing to do with this, especially since this happened with Bucolic Origins too. I will be closing this since this is probably out of my control. Also, just for the future, apoli = origins (basically).
