### ISSUE TITLE
Compatibility with bodacious berries

### ISSUE THREAD

**Issue by slavalamp** [mosharky/GroundedOrigins#15]
**Description**
Hi! Could you make berries from the [bodacious berries](https://modrinth.com/mod/berries) mod count as berry-related things for the Deer origin?

**Comment by mosharky** [comment]
You'll have to follow the guide I made [here](https://github.com/Mos-Origins/GroundedOrigins/wiki#editing-tags). Unfortunately, if I were to do that, it would make anyone who doesn't have that mod crash, so it's up to you/the modpack author to work on this.
