### ISSUE TITLE
Penguin Origin Vanishes When Visiting Nether

### ISSUE THREAD

**Issue by SirSleepySimon** [mosharky/GroundedOrigins#18]
### Minecraft Version

1.18.2

### Mod Version

1.20

### Mod loader

Forge

### Describe your issue

When ever I go into the nether as the penguin origin and click the button to bring up the origins menu the origin will not be showing even though all the normal effects and powers continue to happen.

On a side not is there something we can do to make tinkers construct armour fire protection count for penguins.

**Comment by mosharky** [comment]
Sorry for taking so long. Unfortunately, I'm not supporting 1.18. This issue is probably related to the origins forge port though, not this addon
