### ISSUE TITLE
Deer origin's regeneration ability doesn't work

### ISSUE THREAD

**Issue by Nime91** [mosharky/GroundedOrigins#2]
### Minecraft Version

1.18.1

### Mod Version

1.1.0

### Mod loader

Fabric

### Describe your issue

First encountered this issue when playing Another Quality Modpack 2 (AQM2), but tested it on a fresh version and the issue's still there. The regeneration buff only regenerates when exiting that biome from the lingering buff, but no more after that. Maybe I don't understand how the ability is supposed to work, but this seems like a bug to me and if it isn't, I don't see much use in the Deer origin.

To be clear, it works when you exit the biome, probably because it's counting UP while in the biome and DOWN when you're outside of it. I'm not entirely sure how to solve this issue, but you could either make it so it counts down infinitely while in the biome or so it's a separate passive that is identical to the effects of regeneration, but is actually just a heal over time.

**Comment by mosharky** [comment]
Huh, you're right, I just tested it. This seems like weird behavior on Minecraft's end with the regen effect. I'll see if I can do anything here
