### ISSUE TITLE
Moth's can fly.  How?  I can only glide.

### ISSUE THREAD

**Issue by Konglomneshued** [mosharky/GroundedOrigins#7]
According to the mod, "you are capable of flight".  I can only glide.

**Comment by mosharky** [comment]
Yup, I meant flight as in having an Elytra. I'll change the description in the next update, my bad!

**Comment by Konglomneshued** [comment]
> Yup, I meant flight as in having an Elytra. I'll change the description in the next update, my bad!

Aw

**Comment by Konglomneshued** [comment]
On that note, how do I consume flower stamens.

**Comment by mosharky** [comment]
You can craft Flower Stamens with 1 Spore Blossom or 2 Flowers in a crafting grid. You can eat them like they're any other food, just as long as you're playing as the Moth.

**Comment by Konglomneshued** [comment]
> You can craft Flower Stamens with 1 Spore Blossom or 2 Flowers in a crafting grid. You can eat them like they're any other food, just as long as you're playing as the Moth.

How do I get spore blossoms?

**Comment by mosharky** [comment]
They spawn in the vanilla Lush Caves biome.

**Comment by Konglomneshued** [comment]
Thanks
