### ISSUE TITLE
Moth origin won't climb vertical surfaces

### ISSUE THREAD

**Issue by LoraHadACookie** [mosharky/GroundedOrigins#9]
### Minecraft Version

1.16.5

### Mod Version

v1.0.1

### Mod loader

Forge

### Describe your issue

I selected the Moth origin to play with it in my singleplayer world and I found out pretty fast that I couldn't climb up walls and since the moth is shorter and cant jump one block high it made moving really difficult,  so just wondering if this was a bug or if there was an action I could take to fix it

**Comment by mosharky** [comment]
What do you mean by *cant*? Is it malfunctioning, or does it not work at all? Have you tried pressing the toggle button?

**Comment by LoraHadACookie** [comment]
I don't know which button toggles it because secondary and primary didn't work and the mod doesn't specify which power button to toggle.  I wasn't able to climb up walls at all and I couldn't find which toggle button to use.

**Comment by LoraHadACookie** [comment]
I'm double checking every toggle button.

**Comment by mosharky** [comment]
It's the Quaternary keybind from [Origins Power Expansion](https://www.curseforge.com/minecraft/mc-mods/origins-power-expansion).

**Comment by LoraHadACookie** [comment]
Okay thank you so much!

**Comment by LoraHadACookie** [comment]
That didn't work

**Comment by mosharky** [comment]
so you pressed the keybind and it still didn't work?

**Comment by LoraHadACookie** [comment]
Yeah

**Comment by mosharky** [comment]
And is the key conflicting with anything else? If not, I have no idea why it wouldn't work

**Comment by LoraHadACookie** [comment]
nope it's not conflicting

**Comment by mosharky** [comment]
Well uhh, unfortunately not much I can do here. I'm not supporting older versions since I don't have much time, and this is something that should supposedly work. The Moth origin was heavily tested on my end, and I haven't had anyone report this problem before. I hope you manage to solve this since it seems to be on your end. Try also just running this mod on its own, if its not a problem with your modpack then let me know.

**Comment by LoraHadACookie** [comment]
I'll try that

**Comment by mosharky** [comment]
I'm going to close this now as it doesn't seem to be a problem on my end
